# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXaS4YjUb-syx0dI7n61WtV5iGgny_jT
"""

from PIL import Image
from fastai.vision.all import *

import pickle
with open("/content/drive/MyDrive/Projectmodel/mymodel.pkl","rb") as f:
  mmm = pickle.load(f)

def test_external_image(img_path):
    img = PILImage.create(img_path)
    img.show()
    pred_class, pred_idx, outputs = mmm.predict(img)
    print(f"Predicted class: {pred_class}")
    print(f"Prediction index: {pred_idx}")
    print(f"Model output probabilities: {outputs}")

    plt.title(f"Predicted: {pred_class}")
    plt.imshow(img)
    plt.axis('off')
    plt.show()

# Example usage:
test_image_path = '/content/drive/MyDrive/Projectmodel/predict/download (1).jpeg'
test_external_image(test_image_path)

from google.colab import drive
drive.mount('/content/drive')